// Developer: Shadow Coderr, Architect
import { PageSnapshot, ElementLocator } from '../types/capture';

export class POMGenerator {
  /**
   * Generates a Playwright Page Object Model (POM) from a page snapshot
   */
  generate(snapshot: PageSnapshot): string {
    const { metadata, locators } = snapshot;
    const className = this.toPascalCase(metadata.pageName || 'Page');
    
    let code = `import { Page, Locator, expect } from '@playwright/test';\n\n`;
    code += `/**\n * Page Object Model for ${metadata.url}\n * Generated by ContextGraph on ${metadata.timestamp}\n */\n`;
    code += `export class ${className} {\n`;
    code += `  private readonly page: Page;\n`;
    
    // Add locators as private properties
    const uniqueLocators = this.filterUniqueLocators(locators.elements);
    
    uniqueLocators.forEach((el, index) => {
      const propertyName = this.toCamelCase(this.getElementName(el, index));
      code += `  public readonly ${propertyName}: Locator;\n`;
    });

    code += `\n  constructor(page: Page) {\n`;
    code += `    this.page = page;\n`;
    
    // Initialize locators
    uniqueLocators.forEach((el, index) => {
      const propertyName = this.toCamelCase(this.getElementName(el, index));
      const bestLocator = el.locators[0]?.value || `page.locator('${el.tagName}')`;
      code += `    this.${propertyName} = ${bestLocator};\n`;
    });
    
    code += `  }\n\n`;

    // Add navigation method
    code += `  async goto() {\n`;
    code += `    await this.page.goto('${metadata.url}');\n`;
    code += `  }\n\n`;

    // Add basic actions for inputs
    uniqueLocators.filter(el => ['input', 'textarea', 'select'].includes(el.tagName)).forEach((el, index) => {
      const propertyName = this.toCamelCase(this.getElementName(el, index));
      const actionName = el.tagName === 'select' ? 'select' : 'fill';
      code += `  async ${actionName}${this.toPascalCase(propertyName)}(value: string) {\n`;
      code += `    await this.${propertyName}.${actionName}(value);\n`;
      code += `  }\n\n`;
    });

    // Add click actions for buttons and links
    uniqueLocators.filter(el => ['button', 'a'].includes(el.tagName) || el.attributes['role'] === 'button').forEach((el, index) => {
      const propertyName = this.toCamelCase(this.getElementName(el, index));
      code += `  async click${this.toPascalCase(propertyName)}() {\n`;
      code += `    await this.${propertyName}.click();\n`;
      code += `  }\n\n`;
    });

    code += `}\n`;
    
    return code;
  }

  private getElementName(el: ElementLocator, index: number): string {
    // Try to get a meaningful name from attributes or text
    const name = el.attributes['name'] || 
                 el.attributes['id'] || 
                 el.attributes['data-testid'] || 
                 el.attributes['aria-label'] ||
                 el.text?.trim().substring(0, 20) ||
                 `${el.tagName}${index}`;
    
    return name.replace(/[^a-zA-Z0-9]/g, '_');
  }

  private filterUniqueLocators(elements: ElementLocator[]): ElementLocator[] {
    const seen = new Set<string>();
    return elements.filter(el => {
      const name = this.getElementName(el, 0);
      if (seen.has(name)) return false;
      seen.add(name);
      return true;
    }).slice(0, 50); // Limit to top 50 elements for POM
  }

  private toCamelCase(str: string): string {
    return str.replace(/(?:^\w|[A-Z]|\b\w)/g, (word, index) => {
      return index === 0 ? word.toLowerCase() : word.toUpperCase();
    }).replace(/\s+/g, '').replace(/_/g, '');
  }

  private toPascalCase(str: string): string {
    const camel = this.toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}
